### ISSUE TITLE
Enhance cv.aglm() for tuning alpha

### ISSUE THREAD

**Issue by kkondo1981** [kkondo1981/aglm#11]
I believe it's better for us to investigate external libraries such as caret and try to provide some interfaces for them which is enough to tune alpha of aglm, because writing grid search from scratch is slightly troublesome. If such approach is not likely to work well, we would try to write it by ourself from scratch.

**Comment by iwahiropuzzles** [comment]
I think that the way of calculation by caret is inefficient when you use it for the grid search on alpha and lambda at the same time for glmnet. The point is that the glmnet function is slow when you supply a single value for lambda (but the grid search does repeat "supplying a single value for lambda").

**Comment by kkondo1981** [comment]
Thank you for your advice, Iwasawa-san.
I understood your point. Maybe measuring time of glmnet for enough size of design matrices is the first task.

**Comment by iwahiropuzzles** [comment]
By the way, you should anyway examine what `glmnetUtils::cva.glmnet` can do.

**Comment by kkondo1981** [comment]
Implemented base function in #35 .
I will do more works for parallel computations, etc soon.

**Comment by kkondo1981** [comment]
Done in #61.
