### ISSUE TITLE
Small changes

### ISSUE THREAD

**Issue by iwahiropuzzles** [kkondo1981/aglm#14]
https://github.com/kkondo1981/aglm/blob/633d9d5b8a118ea649d47f77901ca9b7aafb4088/examples/boston.R#L27
https://github.com/kkondo1981/aglm/blob/2904927d63b821765cf03254da15a24db77d6fba/examples/boston2.R#L37
Can you change both of them to "plot(y_true, y_pred)"?

**Comment by kkondo1981** [comment]
Fixed in #17 . It will be released soon with other fixes.
