### ISSUE TITLE
Doesn't "add_linear_columns = FALSE" work?

### ISSUE THREAD

**Issue by iwahiropuzzles** [kkondo1981/aglm#16]
Try:
library(MASS) # For Boston
library(aglm)
xy <- Boston # xy is a data.frame to be processed.
colnames(xy)[ncol(xy)] <- "y" # Let medv be the objective variable, y.
x <- xy[-ncol(xy)]
y <- xy$y
str(aglm(x, y, add_linear_columns = TRUE)) # Works
str(aglm(x, y, add_linear_columns = FALSE)) # Error?

**Comment by kkondo1981** [comment]
Fixed it in #17 . It will be released soon with other fixes.
