### ISSUE TITLE
Change names?

### ISSUE THREAD

**Issue by iwahiropuzzles** [kkondo1981/aglm#19]
This problem is not at all crucial. But, anyway, it seems that the term "intersection" is sometimes mistakenly used for "interaction". Especially, the argument "add_intersection_columns" should be renamed to "add_interaction_columns", shouldn't it? Or is that intentional?

**Comment by kkondo1981** [comment]
Tank you for telling.
I will fix it soon.

**Comment by kkondo1981** [comment]
Fixed it in #17 . It will be released soon with other fixes.
