### ISSUE TITLE
predict.AccurateGLM with type = "coefficients" or "nonzero"

### ISSUE THREAD

**Issue by iwahiropuzzles** [kkondo1981/aglm#20]
In aglm, exactly as in glmnet, you should be able to use 
`predict(model, type = "coefficients")` and `predict(model, type = "nonzero")`
without  specifying any `newx`. But, at the moment, they are not available in that way. 
(This issue is much less crucial than #18, though.)

**Comment by kkondo1981** [comment]
Fixed in #17 . It will be released soon with other fixes.
