### ISSUE TITLE
Keep fit.preval, etc. in cv.aglm()

### ISSUE THREAD

**Issue by iwahiropuzzles** [kkondo1981/aglm#22]
When `keep = TRUE`, `fit.preval`, etc. must be provided. Two more lines are needed in the following, right?
https://github.com/kkondo1981/aglm/blob/abcd0ce2c7c7443c722341b4e27d161590c87f6b/R/cv-aglm.R#L127-L137

**Comment by kkondo1981** [comment]
Fixed in #17 . It will be released soon with other fixes.
