### ISSUE TITLE
Defaults of type.measure

### ISSUE THREAD

**Issue by iwahiropuzzles** [kkondo1981/aglm#30]
Defaults of `type.measure` seem to have some trouble.

First, try:

>install.packages('CASdatasets',
>                 repos = 'http://cas.uqam.ca/pub/R/',
>                  type='source',
>                  dependencies = TRUE
>                  )
>library(CASdatasets)
>data(ausprivauto0405)
>exy <- ausprivauto0405[1:500, c(1:6, 8)]
>expo <- exy[,1]
>x <- exy[2:6]
>y <- exy[,7]
>model <- cv.aglm(x = x, y = y, offset = log(expo), #type.measure = "deviance",
>  add_interaction_columns = FALSE, family = "poisson")
>model@name

When I tried, the output was:
>  mse 
> "Mean-Squared Error" 

But it should have been:
>  deviance 
>  "Poisson Deviance" 

Compare:

>model <- cv.glmnet(x =  sapply(x, as.numeric), y = y, offset = log(expo), 
>  family = "poisson")
>model$name

Its output:
>  deviance 
>  "Poisson Deviance"

**Comment by kkondo1981** [comment]
@iwahiropuzzles please try #31
