### ISSUE TITLE
An additional option of plot.AccurateGLM

### ISSUE THREAD

**Issue by iwahiropuzzles** [kkondo1981/aglm#32]
As we can get the coefs for a particular lambda by either `coef(aglm(x, y,...), s = lambda)` or  `coef(cv.aglm(x, y,...), s = lambda)`, can you make `plot.AccurateGLM` possible to produce the plots for a particular lambda by `plot(aglm(x, y,...), s = lambda)` or  `plot(cv.aglm(x, y,...), s = lambda)`?

**Comment by kkondo1981** [comment]
Can you explain which kind of plots are expected　and how it works when `s` is not given?

**Comment by iwahiropuzzles** [comment]
>Can you explain which kind of plots are expected

When `lambda` is a single value, `plot(aglm(x, y, lambda = lambda, ...))` (without `s =`) is already available.
So, I can say,  `plot(aglm(x, y, lambda = lambda.list, ...), s = lambda)` should produce roughly the same plots as `plot(aglm(x, y, lambda = lambda, ...))` does, where `lambda.list` is a vector an element of which is `lambda`.
Only the differences between the two sets of plots are tiny computational differences.

**Comment by kkondo1981** [comment]
@iwahiropuzzles Thank you for your clarification, and I realized that there is no need to plot for multiple lambda values in one `plot.AccurateGLM` call? In other words, your intention is to plot coefficients corresponding to one lambda value, with one aglm object trained with multiple lambda values?

If my understanding is true, the implementation will be straightforward and nothing is cost.

**Comment by iwahiropuzzles** [comment]
Yes, you seem to understand what I mean. Thanks.
