### ISSUE TITLE
Another additional option of plot.AccurateGLM

### ISSUE THREAD

**Issue by iwahiropuzzles** [kkondo1981/aglm#33]
In the current version, there is no other choice but we get all the plots when we use the `plot.AccurateGLM` function. Can you, however, make this function possible to produce the plot of only a chosen variable by something like `plot(aglm(x, y,...), var_name = var_name)` in which `var_name` is the name (or the number?) of the variable?

**Comment by kkondo1981** [comment]
Yes. I will implement it.
