### ISSUE TITLE
install_github in case of not installing glmnet

### ISSUE THREAD

**Issue by kazuzowo** [kkondo1981/aglm#36]
have to set dependencies...

> devtools::install_github("kkondo1981/aglm", build_vignettes=TRUE)
Downloading GitHub repo kkondo1981/aglm@master
✔  checking for file ‘/private/var/folders/3w/zy8n5vsd1cqcfjd42sq_ynk40000gn/T/RtmpMsenAR/remotes2996349476dc/kkondo1981-aglm-16bcb01/DESCRIPTION’ ...
─  preparing ‘aglm’:
✔  checking DESCRIPTION meta-information ...
    as.POSIXlt.POSIXct(x, tz) で警告がありました: 
     unknown timezone 'zone/tz/2019a.1.0/zoneinfo/Asia/Tokyo'
─  checking for LF line-endings in source and make files
─  checking for empty or unneeded directories
─  building ‘aglm_0.3.0.tar.gz’
   
 strptime(xx, f <- "%Y-%m-%d %H:%M:%OS", tz = tz) で警告がありました: 
  unknown timezone 'zone/tz/2019a.1.0/zoneinfo/Asia/Tokyo'
* installing *source* package ‘aglm’ ...
** R
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘glmnet’
ERROR: lazy loading failed for package ‘aglm’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/aglm’
 i.p(...) でエラー: 
   (警告から変換されました) installation of package ‘/var/folders/3w/zy8n5vsd1cqcfjd42sq_ynk40000gn/T//RtmpMsenAR/file299670b35ce3/aglm_0.3.0.tar.gz’ had non-zero exit status

**Comment by kkondo1981** [comment]
@kazuzowo 
Sorry for late response, but I fixed the issue in #37 .
Please try this version as:
> devtools::install_github("kkondo1981/aglm_#_37", build_vignettes=TRUE)

Note that you should remove two underscore surrounding hash mark(#) when executing the above code, because it's placed just for turning off the tagging of Github's markdown.

**Comment by kazuzowo** [comment]
I confirmed the issue has been fixed, thank you.
